name: Streamlit App Action

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Streamlit App Action
        uses: streamlit/streamlit-app-action@v0.0.3

